Create NFT Project Guide
onflow/docs pull request #414
Opened 2023-10-18 00:20 UTC by chasefleming

Addresses: https://github.com/onflow/docs/issues/413

2023-10-18 22:59 UTC, gregsantos requested changes
few comments then looks good to gizzo

2023-10-18 22:59 UTC, gregsantos commented on docs/guides/nft.md
> +	/tests
```suggestion
/cadence
    /contracts
    /scripts
    /transactions
    /tests
```

2023-10-18 22:59 UTC, gregsantos commented on docs/guides/nft.md
> +For security reasons, you might not want to expose all the functions of the Collection to everyone. Instead, you can create an [interface](https://developers.flow.com/cadence/language/interfaces) tha
🔥

2023-10-18 22:59 UTC, gregsantos commented on docs/guides/nft.md
> +To ensure compatibility and interoperability within the Flow ecosystem, it's crucial that your NFT contract adheres to the [Flow NFT standard](https://github.com/onflow/flow-nft). This standard defin
🙏🏼

2023-10-18 22:59 UTC, gregsantos commented on docs/guides/nft.md
> +### Adding ContractInitializedEvent
```suggestion
### Adding ContractInitialized Event
```

2023-10-18 22:59 UTC, gregsantos commented on docs/guides/nft.md
> +		pub event ContractInitialized()
```suggestion
     pub event ContractInitialized()
```

2023-10-18 22:59 UTC, gregsantos commented on docs/guides/nft.md
> +## Depositing an NFT to a Collection
```suggestion
## Minting and Depositing an NFT to a Collection
```

2023-10-18 22:59 UTC, gregsantos commented on docs/guides/nft.md
> +To deposit an NFT into a collection, create a new transaction file:
```suggestion
To mint and deposit an NFT into a collection, create a new transaction file:
```

2023-10-18 22:59 UTC, gregsantos commented on docs/guides/nft.md
> +Congrats, you did it! You’re now ready to launch the next hot NFT project on Flow.
```suggestion
Congrats, you did it! You’re now ready to launch the next fun NFT project on Flow.
```

2023-10-18 23:45 UTC, chasefleming commented
@gregsantos back to you

2023-10-19 16:59 UTC, gregsantos approved these changes

2023-10-19 17:25 UTC, merged