Generate templates docs
onflow/docs pull request #428
Opened 2023-10-30 22:32 UTC by chasefleming

Docs for: https://github.com/onflow/flow-cli/issues/1233

2023-10-30 22:46 UTC, gregsantos requested changes

2023-10-30 22:46 UTC, gregsantos commented on docs/tools/flow-cli/utils/generate.md
> +  - **Directory**: Specifies the directory in which the contract files will be generated. If not provided, a default directory is used.
Should prob specify what the default directory used is

2023-10-31 15:12 UTC, bthaile commented
Are you going to end up making a "Generate templates" type doc for all flow-cli commands?

2023-10-31 16:07 UTC, chasefleming commented
@bthaile There are docs for most other commands: https://developers.flow.com/tools/flow-cli 

Is this what you're referring to?

2023-12-05 00:56 UTC, chasefleming commented
New PR here: https://github.com/onflow/docs/pull/453

2023-12-05 00:56 UTC, closed without merging