update docs to describe supported cadence doc pragma
onflow/docs pull request #513
Opened 2024-01-12 19:44 UTC by bthaile

Update docs to describe currently supported cadence doc pragma

2024-01-12 21:46 UTC, chasefleming requested changes

2024-01-12 21:46 UTC, chasefleming commented on docs/tools/flow-cli/flix.md
> +It's recommended to use pragma to set the metadata for the script or transaction. More information on [Cadence Doc Pragma FLIP](https://github.com/onflow/flips/blob/main/application/20230406-interact
Can we add one line about what pragma is here for people that don't know? Also, missing a period at the end of the paragraph.

2024-01-12 21:46 UTC, chasefleming commented on docs/tools/flow-cli/flix.md
> +transaction(greeting: String) {
Add a line break here

2024-01-12 21:46 UTC, chasefleming commented on docs/tools/flow-cli/flix.md
> +Cadence v0.42.7 supports more Cadence docs provides more funcationality. Parameters descriptions will populate human readable title and description. Look forward to `parameters` property which is an
"supports more Cadence docs provides more funcationality" needs to be rewrote. Also, typo there. Following sentences need some more clarity as well.

2024-01-12 21:46 UTC, chasefleming commented on docs/tools/flow-cli/flix.md
> +Resulting json when metadata is extracted from Cadence Doc Pragma
Add "The" to the start of the sentence and a colon at the end of this.

2024-01-12 21:46 UTC, chasefleming commented on docs/tools/flow-cli/flix.md
>  ```shell
This needs some text before it now too to separate them and explain the command.

2024-01-14 20:52 UTC, bthaile commented
Thanks for the feedback, updated PR

2024-01-16 17:13 UTC, chasefleming requested changes

2024-01-16 17:13 UTC, chasefleming commented on docs/tools/flow-cli/flix.md
> +A pragma is short for "pragmatic information", it's special instructions to convey informaiton to a processor in this case the utility that generates FLIX.
typo on "informaiton"

2024-01-16 17:13 UTC, chasefleming commented on docs/tools/flow-cli/flix.md
> +Cadence v0.42.7 supports additional Cadence pragma funcationality that FlIX utility can use to generate FLIX. It will support parameters "title" and "description".
typo on "funcationality"

2024-01-16 17:13 UTC, chasefleming commented on docs/tools/flow-cli/flix.md
> +The resulting json metadata is extracted from Cadence Doc Pragma
Add a colon after this sentence.

2024-01-16 17:13 UTC, chasefleming commented on docs/tools/flow-cli/flix.md
> +The resulting FLIX json file after generation
Add a colon following this sentence please.

2024-01-16 17:13 UTC, chasefleming commented on docs/tools/flow-cli/flix.md
> +/---
Is this supposed to be here?

2024-01-16 17:13 UTC, chasefleming commented on docs/tools/flow-cli/flix.md
> +Example of using a prefilled FLIX json file. No need to use Cadence pragma when using a prefilled FLIX json file. This method separates FLIX specific information from the transaction or script Cadenc
Add a colon following this.

2024-01-18 22:11 UTC, chasefleming approved these changes

2024-01-18 22:11 UTC, chasefleming commented on docs/tools/flow-cli/flix.md
>  Example of json prefill file with message metadata
Add a colon

2024-01-19 16:57 UTC, merged