Update EVM Accounts text
onflow/docs pull request #675
Opened 2024-03-22 20:33 UTC by Aliserag

2024-03-25 20:11 UTC, gregsantos requested changes

2024-03-25 20:11 UTC, gregsantos commented on docs/evm/build/accounts.md
> +3. **Cadence Owned Accounts (COA)**: Bridging Cadence and EVM environments, COAs operate similarly to EOAs but execute transactions directed from Cadence. Created from Cadence without a key, COAs are
```suggestion
3. **Cadence Owned Account (COA)**: COA is a natively supported EVM smart contract wallet type owned by a Flow account and controlled by a Cadence resource. COAs provide powerful primitives which allow bridging and control of assets, including ERC721, ERC-20, and $FLOW native tokens, and ensuring seamless composability across Cadence and EVM environments. Unlike EVM Contract Accounts, COAs can initiate transactions on their own without needing an external EOA transaction to trigger them.

**Key Features:**

- COAs are exclusively created via Cadence, assigned unique 20-byte EVM addresses based on their UUID.
- COAs can initiate and execute EVM transactions, deploy Solidity contracts from Cadence, and perform other EVM interactions, with their associated EVM address acting as `tx.origin`, and without need of an EOA trigger
- They support native cross-VM bridging capabilities for a variety of tokens, detailed in the [Flow VM Bridge improvement proposal](https://github.com/onflow/flips/pull/233).
- COAs provide dual interfaces for interaction within Flow EVM and Cadence environments. Additional details can be found in the [EVM Support FLIP](https://github.com/onflow/flips/blob/d01024385bf72e8d566f2502c343780603624210/protocol/20231116-evm-support.md#cadence-owned-account-coa)
```

2024-03-25 20:11 UTC, gregsantos commented on docs/evm/build/accounts.md
>  1. **Externally Owned Accounts (EOA)**: EOAs are controlled by private individuals using cryptographic keys and can initiate transactions directly. They are the primary account type for users to inte
```suggestion
1. **Externally Owned Account (EOA)**: An Externally Owned Account (EOA) is a user-controlled account type that operates through cryptographic keys. These accounts are fundamental for user interactions with the blockchain, as they are capable of directly initiating transactions. EOAs serve as the primary gateway for users, allowing them to manage, send, and receive cryptocurrencies, as well as interact with smart contract functionalities.
```

2025-01-08 15:38 UTC, briandoyle81 commented
@Aliserag what's the status of this PR?

2025-09-29 17:15 UTC, briandoyle81 commented
@Aliserag closing as stale, feel free to reopen!

2025-09-29 17:15 UTC, closed without merging